### ISSUE TITLE
custom barcodes as extra options in shiny

### ISSUE THREAD

**Issue by splaisan** [comoto-pasteur-fr/DNABarcodeCompatibility#5]
Dear maintainer,

The tools looks very interesting.
We face issues with different libraries from different customers where we fear barcode overlap.
I did not test the tool yet and the name seems promising for that purpose.

I have also a request for a future version or comment when this could already be done.
I would like to add custom barcode list(s) to the package and shiny popup selector so that we do not need to upload them at each run.
The Broad Institute Crispr barcode sets are more and more used here and it would be cool if we could call them from the selector.
Is it possible to edit the package code and add more named collections?
Alternatively, could the code be changed to look for text files in a default location and create extra collection(s) from them at runtime?
Thanks for your feedback
Stephane

**Comment by etournay** [comment]
Dear Stephane, 

I thank you for your interest in our tools.
What you propose would certainly be useful and we will discuss this with my team for the next release by the end of October 2019.
In the meantime, you could use DNABarcodeCompatibility within R scripts as the package, which is available from Bioconductor, is meant to be scriptable. This way, you could run your tests in batches.
Best wishes, 
Raphael

**Comment by splaisan** [comment]
Thanks Raphael and for the great initiative of sharing your tools via Shiny (wish there would be more out there),
I will look at doing it in R directly with the package and info from the vignette.
Best regards
